Test: randoop.jodatime.RandoopTest3.test195
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test487]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test487
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test474]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test356
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest1.test467]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test474
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test356]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest1.test467
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest0.test498]
The revealed different behavior: PASS
when executed after: []

